### ISSUE TITLE
Invisible wall just past the big slime monster

### ISSUE THREAD

**Issue by johnmcfarlane** [sciencedude200/dungeon-escape#3]
After defeating the big square green slime monster, I want to go to the next room where the round yellow monsters sit still. The hole in the wall is three blocks wide, but I can only fit through two blocks. I think there's an invisible wall in the way. I've marked it with a red cross.
![image](https://user-images.githubusercontent.com/734007/110203864-4092e780-7e68-11eb-894b-7af4ec591a24.png)

**Comment by sciencedude200** [comment]
I fixed it by changing it to a non wall block and now you have to defeat the slime boss to go through the door

**Comment by sciencedude200** [comment]
@johnmcfarlane i think i fixed the bug

**Comment by johnmcfarlane** [comment]
Thanks, @sciencedude200. I checked and the bug is definitely fixed so I'll close the issue now.
